### PR TITLE
Adds flickr effect

### PR DESCRIPTION
**Pull request by oliverturner**

### CODE REVIEW

**Comment by helenemartin** [comment]
Oliver, I do I fork your branch please? I couldn't check that yesterday sorry

**Comment by oliverturner** [comment]
_If_ the code works for you, simply merge the Pull Request

**Comment by oliverturner** [comment]
You can check whether you're happy with the PR by simply downloading a zip from my fork (click the button marked "clone or download", then "Download Zip") and running it locally.

**Comment by helenemartin** [comment]
I looked for the clone button but can't find it. no worries I will change manually thanks!

**Comment by helenemartin** [comment]
I have merged but I can't see the change. Is it on the master branch?
Sorry for the hassle

**Comment by helenemartin** [comment]
Doing it manually.. hope there won't be any conflicts after the merge !!:)

**Comment by oliverturner** [comment]
Changes are here: https://github.com/helenemartin/filmflicker/pull/1/files

**Comment by oliverturner** [comment]
You aren't able to merge if conflicts exist

**Comment by helenemartin** [comment]
Hey Oliver!!!

Maybe at another codebar session you'll show me!

I have copied it manually!

SO GREAT!!! thanks so much!!!

Take care

Hélène

**Comment by helenemartin** [comment]
Sorry another question...
On the original code, the strip was hitting the bottom then looping itself
 It was something like this 
function movePlayer() {
    if (playerY < 625) // what is the top at the moment we should loop back?
    {
      playerY = playerY + 625;
    }
    else {
      playerY = 0;
    }
625 being the pixel number at the flicker level
How do I implement it to the code, please?
I am so thankfull for your help...this presentation totally makes me anxious :(

**Comment by oliverturner** [comment]
The logic in mine is identical: it shifts the filmstrip up by a frame on every call of the `movePlayer` function and loops back to 0 once a threshold is reached... not sure I understand what you're aiming for?

**Comment by helenemartin** [comment]
Ah OK Oliver!!

Sorry

I'd rather have the strip going downwards than upwards!

Is it that I have to play with the y coordinate ? (- or something?)

Please, lemme know

Thanks so much for your help so far!

Cheers

Hélène

**Comment by oliverturner** [comment]
> Is it that I have to play with the y coordinate ? (- or something?)

Yes, exactly.

You probably also want to play with the timing: I had it trigger `movePlayer` once a second just to help me me see what was happening

**Pull request merged**
